name: Update Package.json Version
on:
  workflow_call:
    secrets:
      gh_npm_registry_pat:
        required: true
jobs:
  job:
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    env:
      GH_NPM_REGISTRY_PAT: "${{ secrets.gh_npm_registry_pat }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update Package.json Version
        run: |
          GIT_COMMENT="$(git log -1 --pretty=format:"%s")"
          COMMIT=0

          echo "[INFO] Trying to parse Git comment: ${GIT_COMMENT}"

          if [ "$(echo "${GIT_COMMENT}" | grep 'MAJOR'  -c)" -eq 1 ]; then
            echo "[INFO] Updating MAJOR in package.json"
            BUMP_TYPE="major"
            COMMIT=1
          elif [ "$(echo "${GIT_COMMENT}" | grep 'MINOR' -c)" -eq 1 ]; then
            echo "[INFO] Updating MINOR in package.json"
            BUMP_TYPE="minor"
            COMMIT=1
          elif [ "$(echo "${GIT_COMMENT}" | grep 'PATCH' -c)" -eq 1 ]; then
            echo "[INFO] Updating PATCH in package.json"
            BUMP_TYPE="patch"
            COMMIT=1
          fi

          if [ ${COMMIT} -eq 1 ]; then
            git config user.name "github-actions"
            git config user.email "sys@acierto.com"

            npm version ${BUMP_TYPE} --no-git-tag-version

            git add .
            git commit -m "Update package.json version - By Github Actions"
            git push
          fi
