name: Build Docker Image
on:
  workflow_call:
    inputs:
      image_tag:
        default: 'latest'
        required: true
        type: string
      gcp_registry:
        default: 'eu.gcr.io/internal-cdm/builds'
        required: true
        type: string
      gcp_repository:
        required: true
        type: string
      docker_file:
        default: 'Dockerfile'
        required: true
        type: string
      docker_build_args:
        default: ''
        required: false
        type: string
    secrets:
      gcp_cdm_registry_sa_credentials:
        required: true
      gh_composer_pat:
        required: false
env:
  IMAGE_TAG: ${{ inputs.image_tag }}
  GCP_REGISTRY: ${{ inputs.gcp_registry }}
  GCP_REPOSITORY: ${{ inputs.gcp_repository }}
  DOCKER_FILE: ${{ inputs.docker_file }}
  DOCKER_BUILD_ARGS: ${{ inputs.docker_build_args }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure GCP Credentials
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.gcp_cdm_registry_sa_credentials }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: internal-cdm

      - name: Configure Docker Credentials
        run: |
          gcloud auth configure-docker --quiet

      - name: Build, tag, and push image to GCP GCR
        run: |
          docker build \
            --build-arg GH_COMPOSER_PAT="${{ secrets.gh_composer_pat }}" \
            ${DOCKER_BUILD_ARGS} \
            --tag ${GCP_REGISTRY}/${GCP_REPOSITORY}:${IMAGE_TAG} \
            --tag ${GCP_REGISTRY}/${GCP_REPOSITORY}:latest \
            --file ${DOCKER_FILE} .

          docker push ${GCP_REGISTRY}/${GCP_REPOSITORY}:${IMAGE_TAG}
          docker push ${GCP_REGISTRY}/${GCP_REPOSITORY}:latest
