name: Deploy to Lambda
on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      aws_registry:
        default: ''
        required: true
        type: string
      project_code:
        required: true
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
env:
  IMAGE_TAG: ${{ inputs.image_tag }}
  AWS_REGISTRY: ${{ inputs.aws_registry }}
  PROJECT_CODE: ${{ inputs.project_code }}
jobs:
  job:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${PROJECT_CODE} \
            --image-uri ${AWS_REGISTRY}/${PROJECT_CODE}:${IMAGE_TAG}

          status=0;
          while [ $status != 1 ]
          do
            status=$(aws lambda get-function \
            --function-name ${PROJECT_CODE} \
            --query 'Configuration.[LastUpdateStatus]' \
            | grep -c Successful)
          done
          echo "[INFO] Function deployed"
