name: e2e Automation
on:
  workflow_call:
    inputs:
      project_code:
        required: true
        type: string
      deploy_env:
        required: true
        type: string
      run_command:
        default: ''
        required: true
        type: string
      chrome_version:
        default: ''
        required: true
        type: string
    secrets:
      gh_pull_repo_pat:
        required: true
env:
  PROJECT_CODE: ${{ inputs.project_code }}
  DEPLOY_ENV: ${{ inputs.deploy_env }}
  RUN_COMMAND: ${{ inputs.run_command }}
  CHROME_VERSION: ${{ inputs.chrome_version }}
permissions:
      id-token: write
      contents: write
jobs:
  job:
    timeout-minutes: 360
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout config-management repo
        uses: actions/checkout@v3
        with:
          repository: OCP-Acierto/ocp-config-management
          token: ${{ secrets.gh_pull_repo_pat }}
          path: config

      - name: Execute e2e automation
        run: |         
          export $(grep -v '^#' ./config/${DEPLOY_ENV}/${PROJECT_CODE}/.env | xargs)

          echo "[INFO] Show env variables:
            Project:    ${PROJECT_CODE}
            Deploy Env: ${DEPLOY_ENV}
            Command:    ${RUN_COMMAND}
            "

          npm ci
          npm run ${RUN_COMMAND}
