name: Linter & UnitTest
on:
  workflow_call:
    inputs:
      project_name:
        default: ''
        required: true
        type: string
      max_num_failed_tests:
        default: '1'
        required: false
        type: string
      min_percentage_coverage:
        default: '80'
        required: false
        type: string
    secrets:
      gh_npm_registry_pat:
        required: false
env:
  PROJECT_NAME: ${{ inputs.project_name }}
  MAX_NUM_FAILED_TESTS: ${{ inputs.max_num_failed_tests }}
  MIN_PERCENTAGE_COVERAGE: ${{ inputs.min_percentage_coverage }}
  TZ: CET
jobs:
  job:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      GH_NPM_REGISTRY_PAT: "${{ secrets.gh_npm_registry_pat }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node from package.json
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Instal packages
        run: |
          npm install -g pnpm@${PNPM_VERSION} \
          && pnpm i --frozen-lockfile

      - name: Linter
        env:
          NODE_OPTIONS: "--max_old_space_size=6144"
        run: |
          pnpm run -r lint

      - name: Execute UnitTests
        run: |
          echo "[INFO] Executing unit tests..."
          pnpm test:${PROJECT_NAME}
