name: Linter & UnitTest
on:
  workflow_call:
    inputs:
      max_num_failed_tests:
        default: '1'
        required: false
        type: string
      min_percentage_coverage:
        default: '80'
        required: false
        type: string
    secrets:
      gh_npm_registry_pat:
        required: false
env:
  MAX_NUM_FAILED_TESTS: ${{ inputs.max_num_failed_tests }}
  MIN_PERCENTAGE_COVERAGE: ${{ inputs.min_percentage_coverage }}
jobs:
  job:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      GH_NPM_REGISTRY_PAT: "${{ secrets.gh_npm_registry_pat }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node from package.json
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Instal packages
        env:
          NODE_OPTIONS: "--max_old_space_size=6144"
        run: |
          yarn --frozen-lockfile --no-progress

      - name: Linter
        env:
          NODE_OPTIONS: "--max_old_space_size=6144"
        run: |
          npm run lint

      - name: Execute UnitTests
        run: |
          echo "[INFO] Getting coverage from All files - % Stmts"
          node node_modules/vitest/vitest.mjs  run --coverage \
                     --reporter=json --outputFile=test.json | tee coverage.txt

          coverage=$(cat coverage.txt | grep 'All files' | awk -F'|' '{print $2}' | sed -r 's/\s+//g')

          num_failed_tests=$(cat test.json | jq .numFailedTests)

          if [ "${num_failed_tests}" -gt "${MAX_NUM_FAILED_TESTS}" ]; then
            echo "[ERROR] ${num_failed_tests} Tests Failed, there are only ${MAX_NUM_FAILED_TESTS}
                  allow tests to fail, exit with errlvl 1"
            exit 1
          else
            echo "[INFO] Tests Passed successfully with ${num_failed_tests} failed, continue"
          fi

          if  (( $(echo "$coverage > $MIN_PERCENTAGE_COVERAGE" | bc -l) )); then
            echo "[INFO] Coverage passed successfully with ${coverage}%, continue"
          else
            echo "[ERROR] Coverage ${coverage} is less than the minimum of ${MIN_PERCENTAGE_COVERAGE},
                  exit with errlvl 1"
            exit 1
          fi
