name: Clean Cache GCP CDN
on:
  workflow_call:
    inputs:
      gcp_cdn_project:
        default: ''
        required: true
        type: string
      gcp_cdn_lb:
        default: ''
        required: true
        type: string
    secrets:
      gcp_cdm_registry_sa_credentials:
        required: true
      gcp_storage_sa_credentials:
        required: true
env:
  GCP_CDN_PROJECT: ${{ inputs.gcp_cdn_project }}
  GCP_CDN_LB: ${{ inputs.gcp_cdn_lb }}
jobs:
  job:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Configure GCP Credentials
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.gcp_cdm_registry_sa_credentials }}

      - name: Clean cache GCP CDN
        run: |
          echo "[INFO] Invalidate cache CDN GCP"
          gcloud compute url-maps invalidate-cdn-cache \
            "cdn" \
            --host "${GCP_CDN_LB}" \
            --path "/*" \
            --project "${{ env.GCP_PROJECT }}"