name: Publish to Chromatic
on:
  workflow_call:
    secrets:
      chromatic_project_token:
        required: true
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn --frozen-lockfile
        env:
          GH_NPM_REGISTRY_PAT: ${{ secrets.GH_NPM_REGISTRY_PAT }}

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
