name: Run sonar scanner
on:
  workflow_call:
    inputs:
      project_code:
        required: true
        type: string
    secrets:
      sonar_token:
        required: true
      sonar_host_url:
        required: true
env:
  PROJECT_CODE: ${{ inputs.project_code }}
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.verbose=true
            -Dsonar.projectKey=core
            -Dsonar.sources=.
            -Dsonar.php.tests.reportPath=/opt/jreport
            -Dsonar.php.coverage.reportPaths=/opt/clover
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.exclusions=public/**
