name: Sonar Scanner
on:
  workflow_call:
    inputs:
      image_tag:
        default: 'latest'
        required: false
        type: string
      project_code:
        required: true
        type: string
      gcp_registry:
        default: 'eu.gcr.io/internal-cdm/images'
        required: true
        type: string
      gcp_repository:
        required: true
        type: string
      docker_file:
        default: 'Dockerfile'
        required: true
        type: string
      docker_build_args:
        default: ''
        required: false
        type: string
      sonar_exclusions:
        default: ''
        required: false
        type: string
      sonar_coverage_exclusions:
        default: ''
        required: false
        type: string
      phpunit_gcp_registry:
        default: ''
        required: false
        type: string
      phpunit_gcp_repository:
        default: ''
        required: false
        type: string
      phpunit_redis:
        default: ''
        required: false
        type: string
      phpunit_mongodb:
        default: ''
        required: false
        type: string
      phpunit_rabbitmq:
        default: ''
        required: false
        type: string
      phpunit_mysql:
        default: ''
        required: false
        type: string
      phpunit_elasticsearch:
        default: ''
        required: false
        type: string
      phpunit_config_path:
        default: ''
        required: false
        type: string
      phpunit:
        required: false
        type: string
    secrets:
      gcp_cdm_registry_sa_credentials:
        required: true
      sonar_token:
        required: true
      sonar_url:
        required: true
      rabbitmq_user:
        required: false
      rabbitmq_pass:
        required: false
      mysql_user:
        required: false
      mysql_pass:
        required: false
      leabank_public_key:
        required: false
      leabank_private_key:
        required: false
      gh_pull_repo_pat:
        required: true
env:
  IMAGE_TAG: ${{ inputs.image_tag }}
  GCP_REGISTRY: ${{ inputs.gcp_registry }}
  GCP_REPOSITORY: ${{ inputs.gcp_repository }}
  PROJECT_CODE: ${{ inputs.project_code }}
  SONAR_URL: ${{ secrets.sonar_url }}
  SONAR_TOKEN: ${{ secrets.sonar_token }}
  SONAR_EXCLUSIONS: ${{ inputs.sonar_exclusions }}
  SONAR_COVERAGE_EXCLUSIONS: ${{ inputs.sonar_coverage_exclusions }}
  PHPUNIT: ${{ inputs.phpunit }}
  PHPUNIT_REDIS: ${{ inputs.phpunit_redis }}
  PHPUNIT_MONGODB: ${{ inputs.phpunit_mongodb }}
  PHPUNIT_RABBITMQ: ${{ inputs.phpunit_rabbitmq }}
  PHPUNIT_MYSQL: ${{ inputs.phpunit_mysql }}
  PHPUNIT_ELASTICSEARCH: ${{ inputs.phpunit_elasticsearch }}
  PHPUNIT_CONFIG_PATH: ${{ inputs.phpunit_config_path }}
  PHPUNIT_GCP_REGISTRY: ${{ inputs.phpunit_gcp_registry }}
  PHPUNIT_GCP_REPOSITORY: ${{ inputs.phpunit_gcp_repository }}
jobs:
  job:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout config-management repo
        uses: actions/checkout@v4
        with:
          repository: OCP-Acierto/shared-config-management
          token: ${{ secrets.gh_pull_repo_pat }}
          path: config-management

      - name: Configure GCP Credentials
        run: |
          # IMPORTANT: SECRET MUST BE IN BASE64
          touch gcp_cdm_registry_sa_credentials.json
          echo "${{ secrets.gcp_cdm_registry_sa_credentials }}" | base64 -d > gcp_cdm_registry_sa_credentials.json

          client_email=$(cat gcp_cdm_registry_sa_credentials.json | jq .client_email  -r)
          project_id=$(cat gcp_cdm_registry_sa_credentials.json | jq .project_id  -r)

          echo "[INFO] Get access to Gcloud ${project_id}"

          gcloud auth activate-service-account "${client_email}" \
            --key-file=gcp_cdm_registry_sa_credentials.json \
            --project="${project_id}"

          echo "[INFO] Use project $(gcloud config list --format=json | jq .core.project -r)"

          rm -Rf gcp_cdm_registry_sa_credentials.json

      - name: Configure Docker Credentials
        run: |
          gcloud auth configure-docker --quiet

      - name: PHPUnit Execution
        if: ${{ env.PHPUNIT == 'true' }}
        run: |
          echo "[INFO] Create phpunit-test network"
          docker network create --driver bridge phpunit-test

          if [ ! -z "${PHPUNIT_MONGODB}" ]; then
            echo "[INFO] Start mongodb container"
            docker run -tid --rm --name mongodb --network phpunit-test \
              -e MONGO_INITDB_ROOT_USERNAME=mongoadmin \
              -e MONGO_INITDB_ROOT_PASSWORD=secret  \
              ${PHPUNIT_MONGODB}
          fi

          if [ ! -z "${PHPUNIT_REDIS}" ]; then
            echo "[INFO] Start redis container"
            docker run -tid --rm --name redis --network phpunit-test \
            ${PHPUNIT_REDIS}
          fi

          if [ ! -z "${PHPUNIT_RABBITMQ}" ]; then
            echo "[INFO] Start rabbitmq container"
            docker run -tid --rm --name rabbitmq --network phpunit-test -e RABBITMQ_DEFAULT_USER=${{ secrets.rabbitmq_user }} -e RABBITMQ_DEFAULT_PASS=${{ secrets.rabbitmq_pass }} \
            ${PHPUNIT_RABBITMQ}
          fi

          if [ ! -z "${PHPUNIT_MYSQL}" ]; then
            echo "[INFO] Start mysql container"
            docker run -tid --rm --name mysql --network phpunit-test -e MYSQL_ROOT_PASSWORD=${{ secrets.mysql_pass }} \
            ${PHPUNIT_MYSQL}
          fi

          if [ ! -z "${PHPUNIT_ELASTICSEARCH}" ]; then
            echo "[INFO] Start elasticsearch container"
            docker run -tid --rm --name elasticsearch --network phpunit-test -e "discovery.type=single-node" \
            ${PHPUNIT_ELASTICSEARCH}
          fi

          LEABANK_MOUNT_FILE=""
          LEABANK_PUBLIC_KEY='${{ secrets.leabank_public_key }}'
          LEABANK_PRIVATE_KEY='${{ secrets.leabank_private_key }}'

          if [ ! -z "${LEABANK_PUBLIC_KEY}" ]; then
            echo "${LEABANK_PRIVATE_KEY}" > leabank-key.pem
            echo "${LEABANK_PUBLIC_KEY}" > leabank-key-public.pem
            LEABANK_MOUNT_FILE="true"
            echo "[INFO] created leabank public & private pem files from secrets"
          else
            echo "[INFO] Skipping leabank pem files"
          fi

          echo "[INFO] Execute phpunit tests"
          PHP_VERSION=$(docker run --rm  --entrypoint php "${PHPUNIT_GCP_REGISTRY}/${PHPUNIT_GCP_REPOSITORY}:${IMAGE_TAG}" -v | awk '/^PHP/ {print $2}' | awk -F. '{print $1"."$2}')
          docker run -t --rm --workdir /app --network phpunit-test \
              -v "$(pwd)/jreport:/opt/jreport" \
              -v "$(pwd)/clover:/opt/clover" \
              -v "$(pwd)/config-management:/config-management" \
              ${LEABANK_MOUNT_FILE:+ -v "$(pwd)/leabank-key-public.pem:/app/storage/certificates/leabank-key-public.pem" } \
              ${LEABANK_MOUNT_FILE:+ -v "$(pwd)/leabank-key.pem:/app/storage/certificates/leabank-key.pem" } \
              "${PHPUNIT_GCP_REGISTRY}/${PHPUNIT_GCP_REPOSITORY}:${IMAGE_TAG}" \
              /bin/bash -e -c "echo [INFO] Delete old PHP source.list && \
              rm -vf /etc/apt/sources.list.d/php.list && \
              curl -s https://packages.sury.org/php/apt.gpg | gpg --dearmor -o /usr/share/keyrings/php-sury.gpg && \
              echo deb [arch=amd64 signed-by=/usr/share/keyrings/php-sury.gpg] https://packages.sury.org/php/ bullseye main > 
                /etc/apt/sources.list.d/php.list && \
              echo [INFO] Install PHP testing tools && \
              apt-get update && apt-get -qq install -y php${PHP_VERSION}-xdebug php${PHP_VERSION}-mongodb && \
              echo [INFO] Copy config /config-management/${PHPUNIT_CONFIG_PATH} && \
              cat /config-management/${PHPUNIT_CONFIG_PATH} > /app/.env.testing && \
              XDEBUG_MODE=coverage /app/vendor/bin/phpunit \
                      --configuration /app/phpunit.xml \
                      --log-junit /opt/jreport/jreport.xml \
                      --coverage-clover /opt/clover/clover.xml \
                      --coverage-text
                  "

      - name: Sonar Scanner Execution
        run: |
          docker run --rm --workdir "/app" \
              -v "$(pwd)/:/app/" \
              -v "$(pwd)/jreport:/opt/jreport" \
              -v "$(pwd)/clover:/opt/clover" \
              -v "$(pwd)/coverage:/opt/coverage" \
              "${GCP_REGISTRY}/${GCP_REPOSITORY}:latest" \
              /bin/bash -e -c "ls && /usr/bin/sonar-scanner \
                      -Dsonar.projectKey=${PROJECT_CODE} \
                      -Dsonar.sources=. \
                      -Dsonar.host.url=${SONAR_URL} \
                      -Dsonar.login=${SONAR_TOKEN} \
                      -Dsonar.sourceEncoding=UTF-8 \
                      -Dsonar.coverage.exclusions=**/*spec.ts,**/**/*spec.ts,**/index.ts,**/*mock.ts,**/__mocks__/*,${SONAR_COVERAGE_EXCLUSIONS} \
                      -Dsonar.exclusions=public/**,${SONAR_EXCLUSIONS} \
                      -Dsonar.clover.reportPath=/opt/clover/clover.xml \
                      -Dsonar.php.coverage.reportPaths=/opt/clover/clover.xml \
                      -Dsonar.coverage.jacoco.xmlReportPaths=/opt/clover/clover.xml
                  "
