name: Upload to S3 FE Assets
on:
  workflow_call:
    inputs:
      aws_s3_bucket_lab:
        default: ''
        required: true
        type: string
      aws_s3_bucket_stage:
        default: ''
        required: true
        type: string
      aws_s3_bucket_non_prod:
        default: ''
        required: true
        type: string
      aws_s3_bucket_prod:
        default: ''
        required: true
        type: string
    secrets:
      aws_access_key_id_lab:
        required: false
      aws_secret_access_key_lab:
        required: false
      aws_access_key_id_stage:
        required: false
      aws_secret_access_key_stage:
        required: false
      aws_access_key_id_non_prod:
        required: false
      aws_secret_access_key_non_prod:
        required: false
      aws_access_key_id_prod:
        required: true
      aws_secret_access_key_prod:
        required: true
env:
  AWS_S3_BUCKET: ${{ inputs.aws_s3_bucket }}
jobs:
  job:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id_lab }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key_lab }}
          aws-region: eu-west-1

      - name: Push Static Files to S3 bucket
        run: |
          echo "[INFO] Copy contents from /src/assets/resources/images/* to S3"
          aws s3 sync /src/assets/resources/images/* ${AWS_S3_BUCKET_LAB} --delete
