name: Upload to S3 FE Assets
on:
  workflow_call:
    inputs:
      aws_s3_bucket:
        default: ''
        required: true
        type: string
      account_id:
        default: ''
        required: false
        type: string
    secrets:
      aws_access_key_id:
        required: false
      aws_secret_access_key:
        required: false
env:
  AWS_S3_BUCKET: ${{ inputs.aws_s3_bucket }}
  ACCOUNT_ID: ${{ inputs.account_id }}
permissions:
      id-token: write
      contents: write
jobs:
  job:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        if: ${{ env.ACCOUNT_ID == '' }}
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: eu-west-1

      - name: Configure AWS credentials via role assumption
        uses: aws-actions/configure-aws-credentials@v2
        if: ${{ env.ACCOUNT_ID != '' }}
        with:
          role-to-assume: "arn:aws:iam::${{ env.ACCOUNT_ID }}:role/gha_oidc_assume_role"
          role-session-name: GithubActions
          aws-region: eu-west-1
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Push Static Files to S3 bucket
        run: |
          echo "[INFO] Copy contents from src/assets/resources/images/* to S3"
          aws s3 sync src/assets/resources/images/ ${AWS_S3_BUCKET} --delete
